# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy web app to Azure Static Web Apps

env:
  APP_LOCATION: "./src/pwa" # location of your client code
  APP_OUTPUT_DIRECTORY: 'out' # directory name of client code build output
  APP_OUTPUT_LOCATION: "./src/pwa/out" # location of client code build output

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        run: |
          yarn
          yarn build
        working-directory: ${{ env.APP_LOCATION }}
      - name: Publish build artifact
        uses: actions/upload-artifact@v3
        with:
          name: pwa
          path: ${{ env.APP_OUTPUT_LOCATION }}
          if-no-files-found: error

  infrastructure:
    runs-on: ubuntu-latest
    name: Deploy Infrastructure
    needs: build
    outputs:
      deploymentToken: ${{ steps.deploy.outputs.deploymentToken }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v1
        id: deploy
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
          region: westeurope
          template: ./infrastructure/azure/resourceGroup.bicep
          parameters: './infrastructure/azure/parameters.json repositoryUrl=${{ github.server_url }}/${{ github.repository }}'
          failOnStdErr: false

  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Deploy Application
    needs: infrastructure
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: pwa
          path: ${{ env.APP_OUTPUT_DIRECTORY }}
      - name: Deploy Application
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ needs.infrastructure.outputs.deploymentToken }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_OUTPUT_DIRECTORY }}
          output_location: ''
          skip_app_build: true

  close:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close
    needs: infrastructure
    steps:
      - name: Close
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ needs.infrastructure.outputs.deploymentToken }}
          action: "close"