name: Build and deploy PWA to Azure Static Web Apps

env:
  SOURCE_LOCATION: "./src/pwa" # location of your client code

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: ${{ env.SOURCE_LOCATION }}/yarn.lock
      - name: Restore
        run: yarn install --frozen-lockfile
        working-directory: ${{ env.SOURCE_LOCATION }}
      - name: Build
        run: yarn build
        working-directory: ${{ env.SOURCE_LOCATION }}
      - name: Publish build artifact
        uses: actions/upload-artifact@v3
        with:
          name: pwa
          path: ${{ env.SOURCE_LOCATION }}/out
          if-no-files-found: error

  infrastructure:
    runs-on: ubuntu-latest
    name: Deploy Infrastructure
    needs: build
    env:
      REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}
    outputs:
      deploymentToken: ${{ steps.deploy.outputs.deploymentToken }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v1
        id: deploy
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
          region: westeurope
          deploymentName: dep-resourceGroup-${{ github.run_id }}
          template: ./infrastructure/azure/resourceGroup.bicep
          parameters: './infrastructure/azure/parameters.json repositoryUrl=${{ env.REPOSITORY_URL }} deploymentId=${{ github.run_id }} deploy=true'
          failOnStdErr: false

  deploy:
    runs-on: ubuntu-latest
    name: Deploy Application
    needs: infrastructure
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: pwa
      - name: Deploy Application
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ needs.infrastructure.outputs.deploymentToken }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: './'
          output_location: ''
          skip_app_build: true
          skip_api_build: true