name: Teardown feature environment

env:  
  WEB_APP_NAME: "stapp-pwademo" # name of static web app resource to use

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:  
  close:
    runs-on: ubuntu-latest
    name: Close environment
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Get SWA deployment token
        uses: azure/CLI@v1
        with:
          inlineScript: |
            SWA_DEPLOYMENT_TOKEN=$(az staticwebapp secrets list -n ${{ env.WEB_APP_NAME }} --subscription ${{ secrets.AZURE_CREDENTIALS.subscriptionId }} -o tsv --query properties.apiKey)
            echo "::add-mask::$SWA_DEPLOYMENT_TOKEN"
            echo SWA_DEPLOYMENT_TOKEN=$SWA_DEPLOYMENT_TOKEN >> $GITHUB_ENV
      - name: Close
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.SWA_DEPLOYMENT_TOKEN }}
          action: "close"